// src/components/WorkerNotifPanel.jsx
// Worker notification panel — messages, salary, advances, bonuses, rejections

import React, { useState } from 'react'
import { C, S } from '../utils/constants'
import { fmtRWF } from '../utils/helpers'

export default function WorkerNotifPanel({
  user, messages, salaries, advances, bonusRequests,
  feeds, logs, sales, expenses,
}) {
  const myId = user.uid || user.id
  const [open, setOpen] = useState(true)
  const [readIds, setReadIds] = useState(() => {
    try { return new Set(JSON.parse(localStorage.getItem('farmiq_wnotif_read') || '[]')) }
    catch { return new Set() }
  })

  function markRead(id) {
    setReadIds(prev => {
      const n = new Set(prev); n.add(id)
      try { localStorage.setItem('farmiq_wnotif_read', JSON.stringify([...n])) } catch (e) {}
      return n
    })
  }
  function markAllRead(ids) {
    setReadIds(prev => {
      const n = new Set(prev); ids.forEach(id => n.add(id))
      try { localStorage.setItem('farmiq_wnotif_read', JSON.stringify([...n])) } catch (e) {}
      return n
    })
  }

  // Build notification list
  const notifs = []

  // Messages from admin (newest first)
  ;[...(messages || [])].reverse().forEach(m => {
    const id = 'msg_' + (m.id || m.date + m.time)
    notifs.push({ id, icon: '📢', label: 'Message from ' + m.from, sub: m.text, time: m.date + (m.time ? ' · ' + m.time : ''), color: '#22c55e', read: readIds.has(id) })
  })

  // Salary updates
  const MON = ['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  ;(salaries || []).filter(s => s.workerId === myId).slice().sort((a, b) => (b.createdAt || '').localeCompare(a.createdAt || '')).forEach(s => {
    const id = 'sal_' + s.id
    const month = MON[s.month] || s.month
    if (s.status === 'paid') {
      notifs.push({ id, icon: '💸', label: 'Salary Paid', sub: `${month} ${s.year} — Net: ${fmtRWF(s.net || s.amount)}`, time: s.paidAt ? s.paidAt.slice(0, 10) : '', color: '#4ade80', read: readIds.has(id) })
    } else if (s.adminApproved) {
      notifs.push({ id, icon: '✅', label: 'Salary Approved', sub: `${month} ${s.year} — ${fmtRWF(s.net || s.amount)} ready for payment`, time: s.adminApprovedAt ? s.adminApprovedAt.slice(0, 10) : '', color: '#60a5fa', read: readIds.has(id) })
    } else if (s.autoGenerated && !s.adminApproved) {
      notifs.push({ id, icon: '⏳', label: 'Salary Pending Approval', sub: `${month} ${s.year} — ${fmtRWF(s.net || s.amount)} awaiting admin`, time: s.createdAt ? s.createdAt.slice(0, 10) : '', color: '#fbbf24', read: readIds.has(id) })
    }
  })

  // Advance updates
  ;(advances || []).filter(a => a.workerId === myId).slice().sort((a, b) => (b.createdAt || '').localeCompare(a.createdAt || '')).forEach(a => {
    const id = 'adv_' + a.id
    if (a.status === 'approved') {
      notifs.push({ id, icon: '💰', label: 'Advance Approved', sub: `${fmtRWF(a.amount)} — ${a.reason || 'Salary advance'}`, time: a.approvedAt ? a.approvedAt.slice(0, 10) : '', color: '#4ade80', read: readIds.has(id) })
    } else if (a.status === 'rejected') {
      notifs.push({ id, icon: '❌', label: 'Advance Rejected', sub: `${fmtRWF(a.amount)}${a.rejectionReason ? ' — ' + a.rejectionReason : ''}`, time: a.rejectedAt ? a.rejectedAt.slice(0, 10) : '', color: '#f87171', read: readIds.has(id) })
    } else {
      notifs.push({ id, icon: '🕐', label: 'Advance Pending', sub: `${fmtRWF(a.amount)} — ${a.reason || 'Awaiting approval'}`, time: a.createdAt ? a.createdAt.slice(0, 10) : '', color: '#fbbf24', read: readIds.has(id) })
    }
  })

  // Bonus updates
  ;(bonusRequests || []).filter(r => r.workerId === myId).slice().sort((a, b) => (b.createdAt || '').localeCompare(a.createdAt || '')).forEach(r => {
    const id = 'bon_' + r.id
    if (r.status === 'approved') {
      notifs.push({ id, icon: '🎁', label: 'Bonus Approved', sub: `${r.reason || 'Bonus'} — will be added to your salary`, time: r.approvedAt ? r.approvedAt.slice(0, 10) : '', color: '#a78bfa', read: readIds.has(id) })
    } else if (r.status === 'rejected') {
      notifs.push({ id, icon: '❌', label: 'Bonus Rejected', sub: r.reason || 'Bonus request', time: r.rejectedAt ? r.rejectedAt.slice(0, 10) : '', color: '#f87171', read: readIds.has(id) })
    } else if (r.status === 'consulted') {
      notifs.push({ id, icon: '💬', label: 'Bonus Under Review', sub: `Admin is reviewing: ${r.reason || 'your request'}`, time: r.consultedAt ? r.consultedAt.slice(0, 10) : '', color: '#60a5fa', read: readIds.has(id) })
    } else {
      notifs.push({ id, icon: '🕐', label: 'Bonus Requested', sub: r.reason || 'Awaiting admin review', time: r.createdAt ? r.createdAt.slice(0, 10) : '', color: '#fbbf24', read: readIds.has(id) })
    }
  })

  // Rejected data entries
  ;[[feeds, 'feed', 'Feed Log'], [logs, 'log', 'Daily Report'], [sales, 'sale', 'Sale'], [expenses, 'expense', 'Purchase']].forEach(([arr, type, label]) => {
    ;(arr || []).filter(x => (x.workerId === myId || x.worker === user.name) && x.rejected === true).forEach(x => {
      const id = 'rej_' + type + '_' + x.id
      notifs.push({ id, icon: '✏️', label: `${label} Rejected — Edit & Resubmit`, sub: x.rejectionReason || 'Tap to view in home', time: x.rejectedAt ? x.rejectedAt.slice(0, 10) : '', color: '#f87171', read: readIds.has(id) })
    })
  })

  // Sort: unread first
  notifs.sort((a, b) => (a.read === b.read ? 0 : a.read ? 1 : -1))
  const unreadCount = notifs.filter(n => !n.read).length

  if (notifs.length === 0) return null

  return (
    <div style={{ ...S.card, marginBottom: 14, padding: 0, overflow: 'hidden' }}>
      {/* Header */}
      <div onClick={() => setOpen(o => !o)} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '11px 14px', cursor: 'pointer', userSelect: 'none' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 15 }}>🔔</span>
          <span style={{ fontSize: 13, fontWeight: 700, color: C.text }}>Notifications</span>
          {unreadCount > 0 && (
            <span style={{ background: '#ef4444', color: '#fff', fontSize: 10, fontWeight: 700, borderRadius: 10, padding: '1px 7px', minWidth: 18, textAlign: 'center' }}>
              {unreadCount}
            </span>
          )}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          {unreadCount > 0 && (
            <span onClick={e => { e.stopPropagation(); markAllRead(notifs.map(n => n.id)) }}
              style={{ fontSize: 10, color: C.accent, cursor: 'pointer', textDecoration: 'underline' }}>
              Mark all read
            </span>
          )}
          <span style={{ fontSize: 11, color: C.faint }}>{open ? '▲' : '▼'}</span>
        </div>
      </div>

      {/* List */}
      {open && (
        <div style={{ borderTop: '1px solid ' + C.border, maxHeight: 320, overflowY: 'auto' }}>
          {notifs.map((n, i) => (
            <div key={n.id} onClick={() => markRead(n.id)}
              style={{ display: 'flex', alignItems: 'flex-start', gap: 10, padding: '9px 14px', borderBottom: i < notifs.length - 1 ? '1px solid ' + C.border : 'none', background: n.read ? 'transparent' : 'rgba(255,255,255,.025)', cursor: 'pointer', transition: 'background .2s' }}>
              <span style={{ fontSize: 17, flexShrink: 0, marginTop: 1 }}>{n.icon}</span>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 6 }}>
                  <span style={{ fontSize: 12, fontWeight: n.read ? 500 : 700, color: n.color, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{n.label}</span>
                  {!n.read && <span style={{ width: 6, height: 6, borderRadius: '50%', background: n.color, flexShrink: 0 }} />}
                </div>
                <div style={{ fontSize: 11, color: C.muted, marginTop: 2, lineHeight: 1.4, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{n.sub}</div>
                {n.time && <div style={{ fontSize: 10, color: C.faint, marginTop: 2 }}>{n.time}</div>}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
